# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ShearwaterResearch.ShearwaterCloud
PackageVersion: 2.12.10
PackageLocale: en-US
Publisher: Shearwater Research
PackageName: Shearwater Cloud
License: Proprietary
ShortDescription: Shearwater divers can now link their network of devices and have the flexibility to share information between them all. The power to download and update your dive logs is now in your pocket.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
