# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ShearwaterResearch.ShearwaterCloud
PackageVersion: 2.12.10
InstallerType: nullsoft
Installers:
- Architecture: x86
  InstallerUrl: https://dhitns0xqj1st.cloudfront.net/livedownloads/ShearwaterCloudInstaller_2.12.10.exe
  InstallerSha256: 84BCA69BD3D0F975B0322DD092B48E9B49454FFB6E7D834DD21D3FCCDE1DD2C0
ManifestType: installer
ManifestVersion: 1.12.0
